### PR TITLE
Use new methods to select new date and update today's date

### PR DESCRIPTION
**Pull request by tobiasschweizer**
This PR uses the new methods introduced by https://github.com/angular/material2/pull/11821.

Tagged builds from material2 and cdk are used until this is available in a release.

### CODE REVIEW

**Comment by tobiasschweizer** [comment]
@mmalerba I think this PR can be merged once the necessary changes are available in one of the next releases.

**Comment by tobiasschweizer** [comment]
https://github.com/dhlab-basel/JDNConvertibleCalendarDateAdapter/blob/96ccf44c13146a92e0ab53ce33c8a5ae8a3de5ec/projects/jdnconvertible-calendar-date-adapter/src/lib/jdnconvertible-calendar-date-adapter.spec.ts#L297-L301

@mmalerba Do you think here a fake adapter could be used so the method `today` always behaves the same (like in the test for https://github.com/angular/material2/pull/11821)

Edit: I think what needs to be checked here is if the conversion from the JS Date object into a calendar date is correct. This means that `new Date();` should be behave always the same.

Edit: solved in 
https://github.com/dhlab-basel/JDNConvertibleCalendarDateAdapter/pull/11/commits/1194886a015096361e6ae492e463cbe65693ead3 using jasmine's `mockDate()`

**Comment by tobiasschweizer** [comment]
@mmalerba Do you know which release will contain the changes introduced by angular/material2#11821?

**Comment by mmalerba** [comment]
probably `7.0.0-beta.0` which should be coming in the next week or two. I don't think we plan to do any more `6.x` minors

**Comment by tobiasschweizer** [comment]
@flavens This the PR we can use for version 7 of @knora/search

**Review by flavens — APPROVED** [review]

**Pull request merged**
